version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1" # Define region explicitly

phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify your Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 430118839072.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t expense-tracker .
      - echo "Tagging the Docker image..."
      - docker tag expense-tracker:latest 430118839072.dkr.ecr.$AWS_REGION.amazonaws.com/expense-tracker:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 430118839072.dkr.ecr.$AWS_REGION.amazonaws.com/expense-tracker:latest
      - echo "Build completed."

artifacts:
  files:
    - "**/*"
