name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: "20" # Updated to Node.js version 20

      - name: Install dependencies
        run: |
          npm install  # For Node.js application

      - name: Build Docker image
        run: |
          docker build -t expense-tracker .

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041772527816.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag expense-tracker:latest 041772527816.dkr.ecr.us-east-1.amazonaws.com/expense-tracker:latest

      - name: Push Docker image to ECR
        run: |
          docker push 041772527816.dkr.ecr.us-east-1.amazonaws.com/expense-tracker:latest

      # Uncomment below to deploy to EKS if needed
      # - name: Deploy to EKS
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }} # Add your kubeconfig as a secret
      #   run: |
      #     kubectl apply -f deployment.yaml
      #     kubectl apply -f service.yaml
