name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Match your Docker image Node.js version

      - name: Install dependencies
        run: |
          npm install  # For Node.js application

      - name: Build Docker image
        run: |
          docker build -t expense-tracker .

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 # Set your AWS region
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 041772527816.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag expense-tracker:latest 041772527816.dkr.ecr.$AWS_REGION.amazonaws.com/expense-tracker:latest

      - name: Push Docker image to ECR
        run: |
          docker push 041772527816.dkr.ecr.$AWS_REGION.amazonaws.com/expense-tracker:latest

      - name: Deploy to EKS
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Add your kubeconfig as a secret
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
